# This is the configuration used to check the `Mongoid::Cleaner` source code.

# === Custom Cops ===

require: rubocop-rspec

# === Configuration ===

# --- Linting ---

Lint/UnusedBlockArgument:
  Description: 'Checks for unused block arguments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscore-unused-vars'
  Enabled: false

# --- Metrics ---

Metrics/LineLength:
  Description: 'Limit lines to 120 characters with 10 characters as buffer.'
  Max: 130

# --- Style ---

Style/AsciiComments:
  Description: 'Use only ASCII symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false

Style/CommentIndentation:
  Description: 'Indentation of comments.'
  Enabled: false

Style/ExtraSpacing:
  Description: 'This cop checks for extra/unnecessary whitespaces.'
  Exclude:
    - Guardfile

Style/TrailingBlankLines:
  Description: 'Checks trailing blank lines and final newline.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#newline-eof'
  Enabled: false